projects:
  app:
    schemaPath: ./src/schema.graphql
    extensions:
      endpoints:
        default: https://eu1.prisma.sh/levyzire-f6efe1/demo/dev
  prisma:
    schemaPath: ./src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml