projects:
  app:
    schemaPath: ./src/schema.graphql
    extensions:
      endpoints:
        default: https://esgi-5iw-graphql.herokuapp.com/
  prisma:
    schemaPath: ./src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml