version: '3'
services:

  dbtest:
    image: 'postgres:12-alpine'
    volumes:
      - '../esgi-2020-5iw-pa-apiplatform/docker/postgresql/data:/var/lib/postgresql/data'
#      - './docker/postgresql/data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=apiplatform
      - POSTGRES_USER=apiplatform
      - POSTGRES_PASSWORD=apiplatform


  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - dbtest
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-220-193-133.compute-1.amazonaws.com
            database: d5ivi8ikipvvtt
            schema: public
            user: tnmypcnobbpvmm
            password: 4e08029f7e313e0e59722e467db8a07e0ae5eb563a8ff50d86e55467b7d2757f
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true

  app:
    build: ./
    depends_on:
      - prisma
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    stdin_open: true

  adminer_554:
    container_name: adminer_554-apiplatform
    image: adminer
    restart: always
    ports:
      - 8090:8080
